In [1]:
import pandas as pd

data = {
   'Name:' :['Ali', 'Sueda','Zeynep'],
   'Age: ': ['3', '17', '5'],
   'Countr: ': ['Tr','De','Nl']
}

df = pd.DataFrame(data)
print(df)

    Name: Age:  Countr:
0     Ali     3       Tr
1   Sueda    17       De
2  Zeynep     5       Nl

In [25]:
import pandas as pd
df = pd.read_excel("uzun_ogrenci_verileri.xlsx")

In [26]:
print(df)

     ogrenci_id    isim   yas   not  devam_yuzdesi  calisma_saati  \
0          1001   Derya  20.0  95.0           80.0            2.3
1          1002    Eren  18.0  66.0           77.0            7.9
2          1003   Defne   NaN   NaN           63.0            1.8
3          1004   Selin  22.0  66.0           66.0            8.7
4          1005    Mert  18.0  90.0           55.0            7.2
..          ...     ...   ...   ...            ...            ...
145        1146    İrem  20.0  63.0            NaN            7.1
146        1147     Ece  18.0  72.0           90.0           13.7
147        1148  Zeynep  18.0  99.0           77.0            5.9
148        1149   Derya  21.0  70.0           70.0            8.2
149        1150     Can  20.0  81.0           93.0           12.0

     sinav_sayisi  proje_puani
0               4         53.0
1               2         59.0
2               3         52.0
3               2         90.0
4               3          NaN
..            ...          ...
145             1         74.0
146             1         67.0
147             1         89.0
148             4         57.0
149             1         88.0

[150 rows x 8 columns]

In [27]:
df.head()

,ogrenci_id,isim,yas,not,devam_yuzdesi,calisma_saati,sinav_sayisi,proje_puani
0,1001,Derya,20.0,95.0,80.0,2.3,4,53.0
1,1002,Eren,18.0,66.0,77.0,7.9,2,59.0
2,1003,Defne,NaN,NaN,63.0,1.8,3,52.0
3,1004,Selin,22.0,66.0,66.0,8.7,2,90.0
4,1005,Mert,18.0,90.0,55.0,7.2,3,NaN

In [28]:
df.describe()

,ogrenci_id,yas,not,devam_yuzdesi,calisma_saati,sinav_sayisi,proje_puani
count,150.000000,142.000000,140.000000,143.000000,141.000000,150.000000,144.000000
mean,1075.500000,20.570423,75.614286,77.832168,8.496454,2.433333,73.284722
std,43.445368,1.987185,15.244098,12.213469,4.273430,1.095547,15.415759
min,1001.000000,18.000000,45.000000,55.000000,1.200000,1.000000,50.000000
25%,1038.250000,19.000000,66.000000,67.000000,5.000000,1.000000,59.000000
50%,1075.500000,20.000000,76.000000,79.000000,8.800000,2.000000,73.000000
75%,1112.750000,22.000000,89.000000,88.000000,12.400000,3.000000,86.000000
max,1150.000000,24.000000,100.000000,100.000000,15.000000,4.000000,100.000000

In [29]:
df.columns

Index(['ogrenci_id', 'isim', 'yas', 'not', 'devam_yuzdesi', 'calisma_saati',
       'sinav_sayisi', 'proje_puani'],
      dtype='object')

In [32]:
df[["isim","not"]]

       isim   not
0     Derya  95.0
1      Eren  66.0
2     Defne   NaN
3     Selin  66.0
4      Mert  90.0
..      ...   ...
145    İrem  63.0
146     Ece  72.0
147  Zeynep  99.0
148   Derya  70.0
149     Can  81.0

[150 rows x 2 columns]

In [34]:
df[df["not"]== 100]

,ogrenci_id,isim,yas,not,devam_yuzdesi,calisma_saati,sinav_sayisi,proje_puani
144,1145,Eren,24.0,100.0,79.0,6.5,4,91.0

In [49]:
gecenler = df.loc[(((df["not"] + df["proje_puani"])/2)>50 )&( df["devam_yuzdesi"] >= 70)]
gecenler[["ogrenci_id","isim"]]

     ogrenci_id    isim
0          1001   Derya
1          1002    Eren
6          1007   Melis
7          1008   Selin
8          1009   Selin
..          ...     ...
144        1145    Eren
146        1147     Ece
147        1148  Zeynep
148        1149   Derya
149        1150     Can

[91 rows x 2 columns]

In [50]:
gecenler.dropna()

,ogrenci_id,isim,yas,not,devam_yuzdesi,calisma_saati,sinav_sayisi,proje_puani
0,1001,Derya,20.0,95.0,80.0,2.3,4,53.0
1,1002,Eren,18.0,66.0,77.0,7.9,2,59.0
6,1007,Melis,19.0,82.0,88.0,5.9,1,96.0
8,1009,Selin,24.0,89.0,79.0,3.0,4,96.0
10,1011,Mert,23.0,98.0,99.0,9.7,4,83.0
...,...,...,...,...,...,...,...,...
144,1145,Eren,24.0,100.0,79.0,6.5,4,91.0
146,1147,Ece,18.0,72.0,90.0,13.7,1,67.0
147,1148,Zeynep,18.0,99.0,77.0,5.9,1,89.0
148,1149,Derya,21.0,70.0,70.0,8.2,4,57.0
149,1150,Can,20.0,81.0,93.0,12.0,1,88.0

In [55]:

gecenler.assign(
    ortalama = ((df["not"] + df["proje_puani"])/2)
).sort_values("ortalama", ascending = False)

,ogrenci_id,isim,yas,not,devam_yuzdesi,calisma_saati,sinav_sayisi,proje_puani,ortalama
40,1041,Defne,22.0,93.0,77.0,11.4,4,100.0,96.5
144,1145,Eren,24.0,100.0,79.0,6.5,4,91.0,95.5
90,1091,Derya,23.0,89.0,80.0,14.1,2,99.0,94.0
147,1148,Zeynep,18.0,99.0,77.0,5.9,1,89.0,94.0
75,1076,Ayşe,21.0,87.0,98.0,2.1,3,98.0,92.5
...,...,...,...,...,...,...,...,...,...
34,1035,Ali,22.0,50.0,75.0,1.2,3,60.0,55.0
87,1088,Ayşe,19.0,57.0,83.0,11.2,4,52.0,54.5
51,1052,Ali,23.0,47.0,99.0,13.5,1,60.0,53.5
114,1115,Ece,23.0,50.0,86.0,12.9,4,54.0,52.0
103,1104,Zeynep,21.0,46.0,91.0,7.6,2,58.0,52.0